### ISSUE TITLE
JUnit5 サポート

### ISSUE THREAD

**Issue by twada** [tddbc/java_junit#15]
[5.0.0-ALPHA](https://github.com/junit-team/junit5/releases/tag/r5.0.0-ALPHA) が出たので、このタイミングでチャレンジするのは面白そうです。プロジェクトは新規に java_junit5 を作っても良いかもしれません。

- [JUnit 5 User Guide](http://junit-team.github.io/junit5/)
- [Release JUnit 5.0.0-ALPHA · junit-team/junit5](https://github.com/junit-team/junit5/releases/tag/r5.0.0-ALPHA)

勇者求む。

**Comment by grimrose** [comment]
使い方ガイドはこちらでまとめられています。

http://qiita.com/opengl-8080/items/40a922bfdd2709aaea1f

**Comment by pocketberserker** [comment]
+1
差異がわかるようにこのリポジトリをコピーして別プロジェクトにするとよさそうな気も？

**Comment by pocketberserker** [comment]
別リポジトリにコミットログごとコピーしてJUnit5対応してみました https://github.com/tddbc/java_junit5/pull/1

**Comment by sue445** [comment]
:+1:

**Comment by twada** [comment]
Great :+1:

**Comment by pocketberserker** [comment]
このissueどうしましょう？閉じてしまいます？
（Hamcrestのサンプルを入れるまでこのissueは閉じないという考え方もある？）

**Comment by twada** [comment]
@pocketberserker さん以外にどなたかが動作検証を行った時点で閉じましょう。 Hamcrest をやるなら別チケットで。

**Comment by pocketberserker** [comment]
@twada 了解です。

**Comment by twada** [comment]
というわけでどなたか動作検証をお願いします!
一通り動いたら issue を閉じてください。

**Comment by irof** [comment]
動作検証しましたー。
一通り動いたので閉じます。

- Mac 
  - gradle(2.11)
  - mvn(3.3.9)
- Windows 8.1 64bit
  - gradlew.bat
  - mvn(3.3.3)

**Comment by twada** [comment]
@irof ありがとうございます！！
